#!/bin/bash

# Test script for Visitor QR Code Validation (Security Endpoint)
# This tests the validation and auto-logging functionality

BASE_URL="${BASE_URL:-http://localhost:3000}"

echo "=========================================="
echo "Visitor QR Code Validation Test"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Step 1: Admin Login
echo "Step 1: Admin Login"
echo "-------------------"

ADMIN_COOKIES="/tmp/test_admin_qr_validation.txt"
rm -f "$ADMIN_COOKIES"

LOGIN_RESPONSE=$(curl -s -X POST "$BASE_URL/api/auth/login" \
    -H "Content-Type: application/json" \
    -d '{"identifier": "admin@example.com", "password": "ChangeMe123!"}' \
    -c "$ADMIN_COOKIES")

if echo "$LOGIN_RESPONSE" | grep -q "error"; then
    echo -e "${RED}❌ Admin login failed${NC}"
    exit 1
else
    echo -e "${GREEN}✅ Admin logged in${NC}"
fi

# Step 2: Get existing QR code from database (if any)
echo ""
echo "Step 2: Check for existing QR codes"
echo "-------------------------------------"

# Note: In a real scenario, QR codes would be generated by tenants
# For testing, we'll check if validation endpoint works with a test QR code
echo -e "${YELLOW}ℹ️  Note: QR code generation requires tenant authentication${NC}"
echo -e "${YELLOW}ℹ️  This test validates the security endpoint structure${NC}"

# Step 3: Test validation endpoint structure
echo ""
echo "Step 3: Test Validation Endpoint"
echo "--------------------------------"

# Test with invalid QR code (should return error)
TEST_RESPONSE=$(curl -s -X POST "$BASE_URL/api/visitor-qr-codes/validate" \
    -H "Content-Type: application/json" \
    -b "$ADMIN_COOKIES" \
    -d '{"qrCode": "invalid-test-code-12345"}')

if echo "$TEST_RESPONSE" | grep -q "error"; then
    ERROR_MSG=$(echo "$TEST_RESPONSE" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data.get('error', 'Unknown'))" 2>/dev/null || echo "Unknown")
    if echo "$ERROR_MSG" | grep -q "Invalid QR code\|not found"; then
        echo -e "${GREEN}✅ Validation endpoint working correctly${NC}"
        echo -e "   Response: $ERROR_MSG"
    else
        echo -e "${YELLOW}⚠️  Unexpected error: $ERROR_MSG${NC}"
    fi
else
    echo -e "${RED}❌ Validation endpoint should return error for invalid code${NC}"
fi

# Step 4: Test preview endpoint
echo ""
echo "Step 4: Test Preview Endpoint"
echo "------------------------------"

PREVIEW_RESPONSE=$(curl -s -X GET "$BASE_URL/api/visitor-qr-codes/validate?qrCode=invalid-test-code" \
    -b "$ADMIN_COOKIES")

if echo "$PREVIEW_RESPONSE" | grep -q "error"; then
    ERROR_MSG=$(echo "$PREVIEW_RESPONSE" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data.get('error', 'Unknown'))" 2>/dev/null || echo "Unknown")
    if echo "$ERROR_MSG" | grep -q "not found"; then
        echo -e "${GREEN}✅ Preview endpoint working correctly${NC}"
        echo -e "   Response: $ERROR_MSG"
    else
        echo -e "${YELLOW}⚠️  Preview response: $ERROR_MSG${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  Preview endpoint returned data (unexpected)${NC}"
fi

echo ""
echo "=========================================="
echo "Test Summary"
echo "=========================================="
echo -e "${GREEN}✅ Validation endpoints are accessible${NC}"
echo -e "${YELLOW}ℹ️  Full testing requires tenant-generated QR codes${NC}"
echo ""
echo "To fully test:"
echo "1. Login as tenant at /tenant/login"
echo "2. Navigate to /tenant/visitor-qr-codes"
echo "3. Generate a QR code"
echo "4. Use the QR code token to test validation"
